import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Auralux",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <head>
        <meta name="viewport" content="width=1024, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                var meta = document.querySelector('meta[name=viewport]');
                var scale = window.innerWidth / 1024;
                if (!meta) {
                  meta = document.createElement('meta');
                  meta.name = 'viewport';
                  document.head.appendChild(meta);
                }
                meta.setAttribute('content', 'width=1024, initial-scale=' + scale + ', maximum-scale=' + scale + ', user-scalable=yes');
              })();
            `,
          }}
        />
      </head>
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  )
}
